version: "3.4"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    restart: on-failure
    environment:
      - SA_PASSWORD=adminpass1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  squaressolver:
    image: squaressolver
    build:
      context: .
      dockerfile: src/SquaresSolver.Api/Dockerfile
      ports:
        - "5000:80"
      depends_on:
        - mssql
  ui:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front_ui
    restart: on-failure
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    volumes:
      - ./front/src:/ui/src
      - "/ui/node_modules"
