version: '3.4'

services:
  squaressolver:
    image: squaressolver
    build:
      context: .
      dockerfile: src/SquaresSolver.Api/Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
