version: "3.4"

services:
  squaressolver.api:
    image: ${DOCKER_REGISTRY-}squaressolverapi
    build:
      context: .
      dockerfile: src/SquaresSolver.Api/Dockerfile
    ports:
      - 8000:80
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
